# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e5944720fc46515758cdf9aa050a92d4999c438006ba5c5aa13831e16bb8d1143fe484ccc57243e51e68ba844ea731ce9da0b0684afbd9c9560f203aec57a0b

test:
  secret_key_base: fe9feddfac0854e97965bb94692ad2ed8d03366c9f123aa999fa713a30bb0eea93ff10e08eb7a8c0b30332712a380d203dd2d297fc10a7e1740435b51f0a3864

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
